import type { GeneratedArtifact, GeometryPrimitive, GeometrySpec, MeshSpec } from "@agent-musaj/core";

export interface GmshGenerationResult {
  artifacts: GeneratedArtifact[];
  command: string;
}

function formatNumber(value: number): string {
  return Number.isInteger(value) ? `${value}` : value.toFixed(6).replace(/0+$/, "").replace(/\.$/, "");
}

function inferDimension(geometry: GeometrySpec): 2 | 3 {
  if (geometry.dimension === 2) {
    return 2;
  }

  return geometry.primitives.some((primitive) => primitive.kind === "box" || primitive.kind === "cylinder" || primitive.kind === "pipe" || primitive.kind === "beam")
    ? 3
    : 2;
}

function buildPrimitive(primitive: GeometryPrimitive, id: number): string {
  const dims = primitive.dimensions;

  switch (primitive.kind) {
    case "box":
      return `Box(${id}) = {0, 0, 0, ${formatNumber(dims.length ?? 1)}, ${formatNumber(dims.width ?? 1)}, ${formatNumber(dims.height ?? 1)}};`;
    case "rectangle":
      return `Rectangle(${id}) = {0, 0, 0, ${formatNumber(dims.width ?? 1)}, ${formatNumber(dims.height ?? 1)}};`;
    case "circle":
      return `Disk(${id}) = {0, 0, 0, ${formatNumber(dims.radius ?? 1)}, ${formatNumber(dims.radius ?? 1)}};`;
    case "cylinder":
      return `Cylinder(${id}) = {0, 0, 0, 0, 0, ${formatNumber(dims.height ?? 1)}, ${formatNumber(dims.radius ?? 1)}};`;
    case "beam":
      return `Box(${id}) = {0, 0, 0, ${formatNumber(dims.length ?? 1)}, ${formatNumber(dims.webThickness ?? 0.2)}, ${formatNumber(dims.flangeThickness ?? 0.2)}};`;
    case "pipe": {
      const outerRadius = dims.outerRadius ?? 1;
      const innerRadius = dims.innerRadius ?? Math.max(outerRadius * 0.7, 0.1);
      const height = dims.height ?? 1;
      return [
        `Cylinder(${id}) = {0, 0, 0, 0, 0, ${formatNumber(height)}, ${formatNumber(outerRadius)}};`,
        `Cylinder(${id + 1}) = {0, 0, 0, 0, 0, ${formatNumber(height)}, ${formatNumber(innerRadius)}};`,
        `BooleanDifference{ Volume{${id}}; Delete; }{ Volume{${id + 1}}; Delete; }`
      ].join("\n");
    }
    default:
      return `// Unsupported primitive "${primitive.kind}"`;
  }
}

function buildGeoScript(geometry: GeometrySpec, mesh: MeshSpec): string {
  const physicalGroupLine = geometry.dimension === 3
    ? `Physical Volume("domain") = {1};`
    : `Physical Surface("domain") = {1};`;
  const lines: string[] = [
    `// Generated by agent-musaj`,
    `SetFactory("OpenCASCADE");`,
    `Mesh.CharacteristicLengthMin = ${formatNumber(mesh.minElementSize)};`,
    `Mesh.CharacteristicLengthMax = ${formatNumber(mesh.maxElementSize)};`,
    `Mesh.ElementOrder = ${mesh.order};`
  ];

  geometry.primitives.forEach((primitive, index) => {
    lines.push(`// Primitive ${index + 1}: ${primitive.label}`);
    lines.push(buildPrimitive(primitive, index + 1));
  });

  if (geometry.primitives.length === 0) {
    lines.push(`// No primitives were inferred from the prompt.`);
  }

  lines.push(physicalGroupLine);

  return lines.join("\n") + "\n";
}

function buildMeshScript(dimension: 2 | 3, geometryName: string): string {
  const flag = dimension === 3 ? "-3" : "-2";
  return [
    "#!/usr/bin/env sh",
    "set -eu",
    `gmsh "${geometryName}.geo" ${flag} -format msh2 -o "${geometryName}.msh"`
  ].join("\n") + "\n";
}

export function generateGmshArtifacts(geometry: GeometrySpec, mesh: MeshSpec): GmshGenerationResult {
  const dimension = inferDimension(geometry);
  const geoContent = buildGeoScript({ ...geometry, dimension }, mesh);
  const command = `gmsh ${geometry.name}.geo ${dimension === 3 ? "-3" : "-2"} -format msh2 -o ${geometry.name}.msh`;

  const artifacts: GeneratedArtifact[] = [
    {
      kind: "gmsh-geo",
      fileName: `${geometry.name}.geo`,
      content: geoContent,
      description: "Gmsh geometry and mesh definition"
    },
    {
      kind: "gmsh-script",
      fileName: `run-${geometry.name}-gmsh.sh`,
      content: buildMeshScript(dimension, geometry.name),
      description: "Shell script for meshing the geometry with Gmsh"
    },
    {
      kind: "manifest",
      fileName: `${geometry.name}.gmsh.manifest.json`,
      content: JSON.stringify(
        {
          geometry: geometry.name,
          dimension,
          command,
          mesh
        },
        null,
        2
      ),
      description: "Machine-readable summary of the Gmsh generation step"
    }
  ];

  return { artifacts, command };
}
