// Generated by agent-musaj
SetFactory("OpenCASCADE");
Mesh.CharacteristicLengthMin = 0.5;
Mesh.CharacteristicLengthMax = 1.5;
Mesh.ElementOrder = 1;
// Primitive 1: beam
Box(1) = {0, 0, 0, 10, 1, 0.5};
Physical Group("domain") = {1};
